### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by kordnddn** [SirHoDo/RocketTrades#2]
~/PeepyLlama$ npm i
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated google-search-autocomplete@1.0.9: No longer maintained
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated snekfetch@3.6.4: use node-fetch instead
npm WARN deprecated discord.js@11.6.4: no longer supported
npm ERR! code 1
npm ERR! path /home/runner/PeepyLlama/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/bin/node /nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/runner/PeepyLlama/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/runner/PeepyLlama/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.1.0
npm ERR! node-pre-gyp info using node@18.16.1 | linux | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/home/runner/PeepyLlama/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for canvas@2.8.0 and node@18.16.1 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.1 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.1 | linux | x64
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Linux 6.2.0-1018-gcp
npm ERR! gyp ERR! command "/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/bin/node" "/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/runner/PeepyLlama/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/runner/PeepyLlama/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd /home/runner/PeepyLlama/node_modules/canvas
npm ERR! gyp ERR! node -v v18.16.1
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/bin/node /nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/runner/PeepyLlama/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/runner/PeepyLlama/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/runner/PeepyLlama/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:72:20)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Linux 6.2.0-1018-gcp
npm ERR! node-pre-gyp ERR! command "/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/bin/node" "/home/runner/PeepyLlama/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/runner/PeepyLlama/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v18.16.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.1.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-11-03T05_59_55_051Z-debug-0.log
Detected change in environment, reloading shell...

**Comment by SirHoDo** [comment]
> ~/PeepyLlama$ npm i
> 
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> 
> npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
> 
> npm WARN deprecated google-search-autocomplete@1.0.9: No longer maintained
> 
> npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> 
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> 
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> 
> npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
> 
> npm WARN deprecated snekfetch@3.6.4: use node-fetch instead
> 
> npm WARN deprecated discord.js@11.6.4: no longer supported
> 
> npm ERR! code 1
> 
> npm ERR! path /home/runner/PeepyLlama/node_modules/canvas
> 
> npm ERR! command failed
> 
> npm ERR! command sh -c node-pre-gyp install --fallback-to-build
> 
> npm ERR! Failed to execute '/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/bin/node /nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/runner/PeepyLlama/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/runner/PeepyLlama/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
> 
> npm ERR! node-pre-gyp info it worked if it ends with ok
> 
> npm ERR! node-pre-gyp info using node-pre-gyp@0.1.0
> 
> npm ERR! node-pre-gyp info using node@18.16.1 | linux | x64
> 
> npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
> 
> npm ERR! node-pre-gyp info check checked for "/home/runner/PeepyLlama/node_modules/canvas/build/Release/canvas.node" (not found)
> 
> npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz
> 
> npm ERR! node-pre-gyp http 404 https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz
> 
> npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz 
> 
> npm ERR! node-pre-gyp WARN Pre-built binaries not found for canvas@2.8.0 and node@18.16.1 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
> 
> npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz 
> 
> npm ERR! gyp info it worked if it ends with ok
> 
> npm ERR! gyp info using node-gyp@9.3.1
> 
> npm ERR! gyp info using node@18.16.1 | linux | x64
> 
> npm ERR! gyp info ok 
> 
> npm ERR! gyp info it worked if it ends with ok
> 
> npm ERR! gyp info using node-gyp@9.3.1
> 
> npm ERR! gyp info using node@18.16.1 | linux | x64
> 
> npm ERR! gyp ERR! find Python 
> 
> npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
> 
> npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
> 
> npm ERR! gyp ERR! find Python checking if "python3" can be used
> 
> npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
> 
> npm ERR! gyp ERR! find Python checking if "python" can be used
> 
> npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
> 
> npm ERR! gyp ERR! find Python 
> 
> npm ERR! gyp ERR! find Python **********************************************************
> 
> npm ERR! gyp ERR! find Python You need to install the latest version of Python.
> 
> npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
> 
> npm ERR! gyp ERR! find Python you can try one of the following options:
> 
> npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
> 
> npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
> 
> npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
> 
> npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
> 
> npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
> 
> npm ERR! gyp ERR! find Python For more information consult the documentation at:
> 
> npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
> 
> npm ERR! gyp ERR! find Python **********************************************************
> 
> npm ERR! gyp ERR! find Python 
> 
> npm ERR! gyp ERR! configure error 
> 
> npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
> 
> npm ERR! gyp ERR! stack     at PythonFinder.fail (/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
> 
> npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
> 
> npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
> 
> npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
> 
> npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
> 
> npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
> 
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
> 
> npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
> 
> npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
> 
> npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> 
> npm ERR! gyp ERR! System Linux 6.2.0-1018-gcp
> 
> npm ERR! gyp ERR! command "/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/bin/node" "/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/runner/PeepyLlama/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/runner/PeepyLlama/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
> 
> npm ERR! gyp ERR! cwd /home/runner/PeepyLlama/node_modules/canvas
> 
> npm ERR! gyp ERR! node -v v18.16.1
> 
> npm ERR! gyp ERR! node-gyp -v v9.3.1
> 
> npm ERR! gyp ERR! not ok 
> 
> npm ERR! node-pre-gyp ERR! build error 
> 
> npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/bin/node /nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/runner/PeepyLlama/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/runner/PeepyLlama/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
> 
> npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/runner/PeepyLlama/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:72:20)
> 
> npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
> 
> npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
> 
> npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
> 
> npm ERR! node-pre-gyp ERR! System Linux 6.2.0-1018-gcp
> 
> npm ERR! node-pre-gyp ERR! command "/nix/store/0g3sc6fhnhsxx8d837kyj06qcbjind1b-nodejs-18.16.1/bin/node" "/home/runner/PeepyLlama/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> 
> npm ERR! node-pre-gyp ERR! cwd /home/runner/PeepyLlama/node_modules/canvas
> 
> npm ERR! node-pre-gyp ERR! node -v v18.16.1
> 
> npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.1.0
> 
> npm ERR! node-pre-gyp ERR! not ok
> 
> 
> 
> npm ERR! A complete log of this run can be found in:
> 
> npm ERR!     /home/runner/.npm/_logs/2023-11-03T05_59_55_051Z-debug-0.log
> 
> Detected change in environment, reloading shell...

Hi there! This repository is 2 years old and using discord.js 11, which has been deprecated for quite some time now. As such, this project is deprecated and won't be receiving updates for the foreseeable future.

If you need help with anything though, message me on discord @ ethanprimmer
